import {
  BiLogoHtml5,
  BiLogoCss3,
  BiLogoJavascript,
  BiLogoTypescript,
  BiLogoReact,
  BiLogoNodejs,
  BiLogoPostgresql,
  BiLogoMongodb,
  BiLogoPython,
  BiLogoDjango,
  BiLogoFlask,
  BiLogoDocker,
  BiLogoFigma,
  BiLogoGit,
} from "react-icons/bi";
import { SiJest } from "react-icons/si";

export default {
  skills: [
    { name: "HTML", icon: BiLogoHtml5 },
    { name: "CSS", icon: BiLogoCss3 },
    { name: "JS", icon: BiLogoJavascript },
    { name: "TS", icon: BiLogoTypescript },
    { name: "React", icon: BiLogoReact },
    { name: "Node", icon: BiLogoNodejs },
    { name: "Python", icon: BiLogoPython },
    { name: "Django", icon: BiLogoDjango },
    { name: "Flask", icon: BiLogoFlask },
    { name: "PostgreSQL", icon: BiLogoPostgresql },
    { name: "MongoDB", icon: BiLogoMongodb },
    { name: "Git", icon: BiLogoGit },
    { name: "Jest", icon: SiJest },
    { name: "Figma", icon: BiLogoFigma },
    { name: "Docker", icon: BiLogoDocker },
  ],
  latestProject: {
    id: "92b24da1-76d7-4dc6-a17f-f14ade23baef",
    title: "Shop Now",
    image: "https://i.imgur.com/fRMWitY.png",
    github: "https://github.com/Derick-Almeida/shop_now-react-ts",
    site: "https://shop-now-dk.vercel.app/",
    hasFrontend: true,
  },
  projects: [
    {
      id: "fa9a2513-444f-470b-84c1-2596ae4b69b3",
      title: "Project Manager",
      image: "https://i.imgur.com/T2XuKDL.jpg",
      github: "https://github.com/Derick-Almeida/api-project_manager-nodejs-ts",
      site: "",
      hasFrontend: false,
    },
    {
      id: "2bbca05c-a1c3-43b1-9ae9-6c2148b655fb",
      title: "NuKenzie",
      image: "https://i.imgur.com/DJciWOM.png",
      github: "https://github.com/Derick-Almeida/nukenzie-react-js",
      site: "https://nukenzie-mu.vercel.app/",
      hasFrontend: true,
    },
    {
      id: "5253c913-a20b-4c30-bf1e-afff1b685040",
      title: "Kimoveis",
      image: "https://i.imgur.com/woJheFg.png",
      github: "https://github.com/Derick-Almeida/api-kimoveis-nodejs-ts",
      site: "",
      hasFrontend: false,
    },
    {
      id: "cad8aec9-564e-46ed-8da1-1cabba65adfd",
      title: "Futcamp",
      image: "https://i.imgur.com/uhQ2IHX.png",
      github: "https://github.com/Derick-Almeida/api-futcamp-django-py",
      site: "",
      hasFrontend: false,
    },
    {
      id: "82592b1e-1601-4cf7-a998-6ffad7a581a8",
      title: "Burger Kenzie",
      image: "https://i.imgur.com/npi9pJq.png",
      github: "https://github.com/Derick-Almeida/burguer_kenzie-react-js",
      site: "https://burguer-kenzie-derick-almeida.vercel.app/",
      hasFrontend: true,
    },
    {
      id: "811dd8b5-620e-469a-a366-fa74a4d733e5",
      title: "KMDB",
      image: "https://i.imgur.com/EYzpwGp.jpg",
      github: "https://github.com/Derick-Almeida/api-kmdb-django-py",
      site: "",
      hasFrontend: false,
    },
  ],
};
